# Generated by Django 4.2.5 on 2023-10-13 20:40

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):
    dependencies = [migrations.swappable_dependency(settings.AUTH_USER_MODEL), ("Learntest", "0001_initial")]

    operations = [
        migrations.CreateModel(
            name="Answer",
            fields=[
                ("id", models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name="ID")),
                ("text", models.CharField(max_length=200)),
            ],
        ),
        migrations.CreateModel(
            name="Category",
            fields=[
                ("id", models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name="ID")),
                ("language_name", models.CharField(default="", max_length=100, unique=True)),
            ],
        ),
        migrations.CreateModel(
            name="MultiQuesModel",
            fields=[
                ("id", models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name="ID")),
                ("question", models.CharField(max_length=200, null=True)),
            ],
        ),
        migrations.CreateModel(
            name="QuestionType",
            fields=[
                ("id", models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name="ID")),
                ("question_type", models.CharField(default="", max_length=100, unique=True)),
            ],
        ),
        migrations.AlterField(model_name="question", name="name", field=models.CharField(max_length=255)),
        migrations.CreateModel(
            name="UserProfile",
            fields=[
                ("id", models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name="ID")),
                ("preferred_language", models.CharField(blank=True, max_length=80, null=True)),
                (
                    "user",
                    models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
                ),
            ],
        ),
        migrations.CreateModel(
            name="SingleQuestion",
            fields=[
                ("id", models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name="ID")),
                ("question_text", models.CharField(max_length=255)),
                ("answer_text", models.CharField(max_length=255)),
                (
                    "language_name",
                    models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to="Learntest.category"),
                ),
                (
                    "question_type",
                    models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to="Learntest.questiontype"),
                ),
            ],
        ),
        migrations.CreateModel(
            name="SingleChoiceQuestion",
            fields=[
                ("id", models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name="ID")),
                ("question_text", models.CharField(max_length=255)),
                (
                    "language_name",
                    models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to="Learntest.category"),
                ),
                (
                    "question_type",
                    models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to="Learntest.questiontype"),
                ),
            ],
        ),
        migrations.CreateModel(
            name="SingleChoiceOption",
            fields=[
                ("id", models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name="ID")),
                ("option_text", models.CharField(max_length=255)),
                ("is_correct", models.BooleanField(default=False)),
                (
                    "question",
                    models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to="Learntest.singlechoicequestion"),
                ),
            ],
        ),
        migrations.CreateModel(
            name="QuestionAnswer",
            fields=[
                ("id", models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name="ID")),
                ("is_correct", models.BooleanField(default=False)),
                ("answer", models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to="Learntest.answer")),
                (
                    "question",
                    models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to="Learntest.multiquesmodel"),
                ),
            ],
        ),
        migrations.CreateModel(
            name="Note",
            fields=[
                ("id", models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name="ID")),
                ("content", models.TextField()),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("user", models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.AddField(
            model_name="multiquesmodel",
            name="answers",
            field=models.ManyToManyField(through="Learntest.QuestionAnswer", to="Learntest.answer"),
        ),
        migrations.AddField(
            model_name="multiquesmodel",
            name="language_name",
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to="Learntest.category"),
        ),
        migrations.AddField(
            model_name="multiquesmodel",
            name="question_type",
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to="Learntest.questiontype"),
        ),
        migrations.CreateModel(
            name="Choice",
            fields=[
                ("id", models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name="ID")),
                ("text", models.CharField(max_length=255)),
                ("is_correct", models.BooleanField(default=False)),
                ("question", models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to="Learntest.question")),
            ],
        ),
    ]
