# Generated by Django 4.2.5 on 2023-10-14 13:10

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [("Learntest", "0002_answer_category_multiquesmodel_questiontype_and_more")]

    operations = [
        migrations.CreateModel(
            name="Quiz",
            fields=[
                ("id", models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name="ID")),
                ("name", models.CharField(max_length=255)),
                ("topic", models.CharField(max_length=255)),
                ("number_of_questions", models.IntegerField()),
                ("time", models.IntegerField(help_text="duration of the quiz in minutes")),
                ("required_score_to_pass", models.IntegerField(help_text="required score to pass")),
            ],
            options={"verbose_name_plural": "Quizes"},
        )
    ]
